# Process to generate release files required for legacy error checks
# Produces a zip file with necessary files
name: Generate Legacy Release Files

on:
  workflow_dispatch:
    inputs:
      modules:
        description: "Comma-deliminated list of modules to prepare for release."
        default: "bds,ds/legacy"
        required: true
      generate_ded:
        description: "Whether or not to generate the DED (true or false)"
        default: "false"
      generate_error_checks:
        description: "Whether or not to organize and generate the error check CSVs (true or false)"
        default: "true"

permissions:
  actions: write
  contents: read
jobs:
  generate-release-files: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up
        run: |
          # install dependencies
          python -m pip install --upgrade pip
          pip install -r tools/csv_tools/requirements.txt

      - name: Generate DEDs
        if: ${{ inputs.generate_ded == 'true' }}
        run: |
          mkdir -p output/DED/

          python tools/csv_tools/combine_form_ded.py \
            --modules ${{ github.event.inputs.modules }} \
            --output-dir output/DED/

      - name: Organize Error Checks
        if: ${{ inputs.generate_error_checks == 'true' }}
        run: |
          mkdir -p output/CSV/

          python tools/csv_tools/prep_for_import.py \
            --modules ${{ github.event.inputs.modules }} \
            --output-dir output/CSV/

      - name: Create Timestamp
        if: ${{ inputs.generate_ded == 'true' || inputs.generate_error_checks == 'true' }}
        id: timestamp
        run: |
          mkdir -p output

          TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT

      - name: Upload artifact
        if: ${{ inputs.generate_ded == 'true' || inputs.generate_error_checks == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.timestamp.outputs.timestamp }}-release-files-legacy
          path: output
